#ifndef _GXGSASAPI_H_
#define _GXGSASAPI_H_

#ifdef    __cplusplus
extern "C" {
#endif    /*    __cplusplus    */

#ifndef GLU64
typedef unsigned long long GLU64;
#endif
#ifndef GLU32
typedef unsigned int GLU32;
#endif
#ifndef GLU16
typedef unsigned short GLU16;
#endif
#ifndef GLU8
typedef unsigned char GLU8;
#endif
#ifndef GLBoolean
typedef int GLBoolean;
#endif

#ifndef TRUE
#define TRUE	1
#endif

#ifndef FALSE
#define FALSE	0
#endif

#if defined(__linux__)
	// Linux Here
	#define DLLEXPORT
	#define STD_CALL 
#else
	// Windows here
	#ifndef DLLEXPORT
		#define DLLEXPORT __declspec(dllexport)
	#endif
	#ifndef STD_CALL
		#define STD_CALL __stdcall
	#endif
#endif

#define SAS_METER_SIZE	8
#define NUM_SUP_SAS_PORT 3
#define MAX_SUP_GAME_NUM 16
#define SAS_EXCEPTION_QUEUE_SIZE	40
#define SAS_VALID_RECORD_QUEUE_SIZE 31

#define GET_LINK_DOWN_TYPE(data_ptr)			(*(GLU8 *)&(((GLU8 *)data_ptr)[0]))

#define GET_EC_QUEUE_FULL_FLAG(data_ptr)		(*(GLU8 *)&(((GLU8 *)data_ptr)[0]))

#define GET_ROMSIG_SEED(data_ptr)				(*(GLU16 *)&(((GLU8 *)data_ptr)[0]))

#define GET_RTE_ENABLE_FLAG(data_ptr)			(*(GLU8 *)&(((GLU8 *)data_ptr)[0]))

#define GET_MACHINE_STATUS(data_ptr)			(*(GLU16 *)&(((GLU8 *)data_ptr)[0]))

#define GET_BILL_DENOM_STATUS(data_ptr)			(*(GLU32 *)&(((GLU8 *)data_ptr)[0]))
#define GET_BILL_DENOM_ACTION_FLAG(data_ptr)	(*(GLU8 *)&(((GLU8 *)data_ptr)[4]))

#define GET_GAME_ENABLE_STATUS(data_ptr)		(*(GLU32 *)&(((GLU8 *)data_ptr)[0]))

#define GET_GAME_DELAY_TIME(data_ptr)			((GLU32)(*(GLU16 *)&(((GLU8 *)data_ptr)[0])) * 100)

#define GET_DATE_TIME_YEAR(data_ptr)			(*(GLU32 *)&(((GLU8 *)data_ptr)[0]))
#define GET_DATE_TIME_MONTH(data_ptr)			(*(GLU32 *)&(((GLU8 *)data_ptr)[4]))
#define GET_DATE_TIME_DATE(data_ptr)			(*(GLU32 *)&(((GLU8 *)data_ptr)[8]))
#define GET_DATE_TIME_HOUR(data_ptr)			(*(GLU32 *)&(((GLU8 *)data_ptr)[12]))
#define GET_DATE_TIME_MIN(data_ptr)				(*(GLU32 *)&(((GLU8 *)data_ptr)[16]))
#define GET_DATE_TIME_SEC(data_ptr)				(*(GLU32 *)&(((GLU8 *)data_ptr)[20]))
#define SAVE_DATE_TIME(data_ptr, user_buf)		memcpy((user_buf), &(((GLU8 *)data_ptr)[0]), 24)

#define GET_REDEEM_RESULT(data_ptr)				(*(GLU8 *)&(((GLU8 *)data_ptr)[0]))
#define GET_REDEEM_TICKET_TYPE(data_ptr)		(*(GLU8 *)&(((GLU8 *)data_ptr)[1]))
#define GET_REDEEM_STATUS(data_ptr)				(*(GLU8 *)&(((GLU8 *)data_ptr)[2]))
#define GET_REDEEM_TICKET_AMOUNT(data_ptr)		(*(GLU64 *)&(((GLU8 *)data_ptr)[3]))
#define GET_REDEEM_CHANGE_AMOUNT(data_ptr)		(*(GLU64 *)&(((GLU8 *)data_ptr)[11]))
#define GET_REDEEM_POOL_ID(data_ptr)			(*(GLU16 *)&(((GLU8 *)data_ptr)[19]))

#define GET_EXT_VALID_STATUS(data_ptr)				(*(GLU8 *)&(((GLU8 *)data_ptr)[0]))

#define GET_SYS_PREP_TICKET_RESULT(data_ptr)					(*(GLU8 *)&(((GLU8 *)data_ptr)[0]))
#define SAVE_SYS_PREP_TICKET_VALID_CODE(data_ptr, user_buf)		memcpy((user_buf), &(((GLU8 *)data_ptr)[1]), 9)

#define GET_VALID_QUEUE_FULL_FLAG(data_ptr)		(*(GLU8 *)&(((GLU8 *)data_ptr)[0]))

#define GET_LEGACY_BONUS_TAX_TYPE(data_ptr)		(*(GLU8 *)&(((GLU8 *)data_ptr)[0]))
#define GET_LEGACY_BONUS_AMOUNT(data_ptr)		(*(GLU64 *)&(((GLU8 *)data_ptr)[1]))

#define GET_AFT_REGISTER_STATUS(data_ptr)					(*(GLU8 *)&(((GLU8 *)data_ptr)[0]))
#define SAVE_AFT_REGISTER_REG_KEY(data_ptr, user_buf)		memcpy((user_buf), &(((GLU8 *)data_ptr)[1]), 20)
#define SAVE_AFT_REGISTER_POS_ID(data_ptr, user_buf)		memcpy((user_buf), &(((GLU8 *)data_ptr)[21]), 4)

#define GET_AFT_LOCK_STATUS(data_ptr)					(*(GLU8 *)&(((GLU8 *)data_ptr)[0]))
#define GET_AFT_LOCK_TRANS_CONDITION(data_ptr)			(*(GLU8 *)&(((GLU8 *)data_ptr)[1]))
#define GET_AFT_LOCK_TIMEOUT(data_ptr)					(*(GLU32 *)&(((GLU8 *)data_ptr)[2]))

#define GET_AFT_HOST_CASHOUT_STATUS(data_ptr)		(*(GLU8 *)&(((GLU8 *)data_ptr)[0]))

#define GET_AFT_TRANS_REJECT_STATUS(data_ptr)		(*(GLU8 *)&(((GLU8 *)data_ptr)[0]))

#define GET_PROG_LINK_STATUS(data_ptr)			(*(GLU8 *)&(((GLU8 *)data_ptr)[0]))
#define GET_PROG_QUEUE_FULL_FLAG(data_ptr)		(*(GLU8 *)&(((GLU8 *)data_ptr)[0]))

#define GET_NVRAM_ERROR_BLOCK_NUM(data_ptr)		(*(GLU16 *)&(((GLU8 *)data_ptr)[0]))

#pragma pack(push, 1)

typedef struct {
	char GameIDStr[3];			// Exact 2 bytes char string
	char AddiIDStr[4];			// Exact 3 bytes char string
	char GameNameStr[21];		// MAX 20 bytes char string
	char PayTableIDStr[7];		// Exact 6 bytes char string
	char PayTableNameStr[21];	// MAX 20 bytes char string
	GLU16 MaxBet;				// 2 bytes binary, MAX 9999
	GLU16 GameOption;			// 2 bytes binary
	GLU16 PayBackPerc;			// 2 bytes binary, MAX 9999
	GLU64 CashoutLimit;			// 8 bytes binary
	GLU16 WagerCatNum;			// 2 bytes binary, MAX 8
} SAS_GAME_DETAIL;

typedef struct {
	GLU8 PortNum;
	GLU8 Type;
	GLU8 Code;
#define MAX_SAS_EXCEPTION_RTE_DATA_SIZE			11
	GLU8 Data[MAX_SAS_EXCEPTION_RTE_DATA_SIZE];
} SAS_EXCEPTION_INFO;

typedef struct {
	GLU8 Type;		// Machine, per game, per denom
	GLU8 Num;		// Game number / Denomination code
	GLU8 Code;		// Meter code
	GLU64 Value;	// 8 bytes binary code (Unit: Cents)
} SAS_METER_INFO;

#define MAX_METER_CLUSTER_SIZE	12

typedef struct {
	GLU8 MeterNum;
	GLU8 Mode[MAX_METER_CLUSTER_SIZE];
	SAS_METER_INFO MeterInfo[MAX_METER_CLUSTER_SIZE];
} SAS_METER_CLUSTER;

typedef struct {
	GLU8 Type;
	GLU8 ProgressiveGroup;
	GLU8 Level;
	GLU64 Amount;		
	GLU64 PartialPay;
	GLU8 ResetID;
} SAS_HANDPAY_INFO;

typedef struct {	
	char TicketLocationStr[41];
	char TicketAddress1Str[41];
	char TicketAddress2Str[41];
	char RestrictedTicketTitleStr[17];
	char DebitTicketTitleStr[17];
	GLU32 CashoutTicketExpir;	
	GLU32 RestrictedTicketExpir;
} SAS_TICKET_DATA;

typedef struct {
	GLU8 TicketType;
	GLU16 TicketNum;	// 2 bytes binary
	GLU32 DateTime[6];	// [0]: Year, [1]: Month, [2]: Date, [3]: Hour, [4]: Minute, [5]: Second
	GLU64 Amount;		// 8 bytes binary. Unit: Cents
	GLU32 Expir;		// 4 bytes binary
	GLU16 PoolID;		// 2 bytes binary
} SAS_TICKET_RECORD;

typedef struct {
	GLU8 IsPartial;
	GLU8 TransType;
	GLU8 TransFlag;
	GLU64 CashAmount;
	GLU64 ResAmount;
	GLU64 NonresAmount;
	GLU32 Expir;
	GLU16 PoolID;
	char TransactionID[21];
} SAS_AFT_TRANS_DATA;

typedef struct {
	char TransSrcDestStr[23];
	char PatronNameStr[23];
	char PatronAcctStr[17];
	GLU64 AcctBalance;
	GLU16 DebitCardNum;
	GLU64 TransFee;
	GLU64 TotalDebitAmount;
	GLU32 Date;
	GLU32 Time;
} SAS_AFT_TRANS_RECEIPT_DATA;

typedef struct {
	char LocationStr[23];
	char Address1Str[23];
	char Address2Str[23];
	char InHouseLine1Str[23];
	char InHouseLine2Str[23];
	char InHouseLine3Str[23];
	char InHouseLine4Str[23];
	char DebitLine1Str[23];
	char DebitLine2Str[23];
	char DebitLine3Str[23];
	char DebitLine4Str[23];
} SAS_AFT_RECEIPT_DATA;

typedef struct {
	GLU8 HitLevel;
	GLU64 Amount;
} SAS_PROG_HIT_DATA;

typedef struct {
	GLU8 PortNum;
	GLU8 Status;
#define SAS_INTR_DATA_SIZE 32
	GLU8 Data[SAS_INTR_DATA_SIZE];
} SAS_INTR_DATA;

#pragma pack(pop)


/* Define bit mask here */
#define BIT_N(n)	((GLU64)0x01 << (n))

// SAS feature
#define BITMASK_SAS_FEATURE_LEGACY_BONUS_AWARDS			BIT_N(0)
#define BITMASK_SAS_FEATURE_VALID_EXTENSION				BIT_N(1)
#define BITMASK_SAS_FEATURE_VALID_MODE_SECURE			BIT_N(2)
#define BITMASK_SAS_FEATURE_VALID_MODE_SYSTEM			BIT_N(3)
#define BITMASK_SAS_FEATURE_TICKET_REDEMPTION			BIT_N(4)
#define BITMASK_SAS_FEATURE_METER_MODEL_WHEN_WIN		BIT_N(5)
#define BITMASK_SAS_FEATURE_METER_MODEL_WHEN_PAID		BIT_N(6)
#define BITMASK_SAS_FEATURE_TICKET_TO_TOTAL_DROP		BIT_N(7)
#define BITMASK_SAS_FEATURE_EXTENDED_METER				BIT_N(8)
#define BITMASK_SAS_FEATURE_AFT							BIT_N(9)
#define BITMASK_SAS_FEATURE_AFT_BONUS_AWARDS			BIT_N(10)
#define BITMASK_SAS_FEATURE_MULTI_DENOM_EXTENSION		BIT_N(11)
#define BITMASK_SAS_FEATURE_TOURNAMENT					BIT_N(12)
#define BITMASK_SAS_FEATURE_COMPONENT_AUTHENTICATION	BIT_N(13)
#define BITMASK_SAS_FEATURE_MULTI_PROG_LP				BIT_N(14)

// SAS machine status
#define BITMASK_SAS_MACHINE_STATUS_ENABLE_PLAY				BIT_N(0)
#define BITMASK_SAS_MACHINE_STATUS_ENABLE_ALL_SOUND			BIT_N(1)
#define BITMASK_SAS_MACHINE_STATUS_ENABLE_GAME_PLAY_SOUND	BIT_N(2)
#define BITMASK_SAS_MACHINE_STATUS_ENABLE_BA				BIT_N(4)
#define BITMASK_SAS_MACHINE_STATUS_LEAVE_MAINTAIN_MODE		BIT_N(5)
#define BITMASK_SAS_MACHINE_STATUS_DISABLE_AUTO_BET			BIT_N(6)

// SAS extended validation status
#define BITMASK_SAS_EXT_VALID_STATUS_USE_PRINTER_FOR_CASHOUT			BIT_N(0)
#define BITMASK_SAS_EXT_VALID_STATUS_USE_PRINTER_FOR_HANDPAY_RECEIPT	BIT_N(1)
#define BITMASK_SAS_EXT_VALID_STATUS_VALID_HANDPAY						BIT_N(2)
#define BITMASK_SAS_EXT_VALID_STATUS_ALLOW_PRINT_RES_TICKET				BIT_N(3)
#define BITMASK_SAS_EXT_VALID_STATUS_ALLOW_PRINT_FOREIGN_RES_TICKE		BIT_N(4)
#define BITMASK_SAS_EXT_VALID_STATUS_ALLOW_TICKET_REDEMPTION			BIT_N(5)

// SAS available transfer status (for AFT)
#define BITMASK_SAS_EGM_AVAIL_TRANS_STATUS_TO_EGM_OK			BIT_N(0)
#define BITMASK_SAS_EGM_AVAIL_TRANS_STATUS_FROM_EGM_OK			BIT_N(1)
#define BITMASK_SAS_EGM_AVAIL_TRANS_STATUS_TO_PRINTER_OK		BIT_N(2)
#define BITMASK_SAS_EGM_AVAIL_TRANS_STATUS_WIN_AMOUNT_PENDING_CASHOUT_TO_HOST	BIT_N(3)
#define BITMASK_SAS_EGM_AVAIL_TRANS_STATUS_BONUS_TO_EGM_OK		BIT_N(4)

// SAS AFT status (for AFT)
#define BITMASK_SAS_EGM_AFT_STATUS_PRINTER_AVAIL_FOR_RECEIPT		BIT_N(0)
#define BITMASK_SAS_EGM_AFT_STATUS_TO_HOST_PARTIAL_AMOUNT_AVAIL		BIT_N(1)
#define BITMASK_SAS_EGM_AFT_STATUS_SUP_CUSTOM_TICKET_DATA			BIT_N(2)
#define BITMASK_SAS_EGM_AFT_STATUS_AFT_REGISTERED					BIT_N(3)
#define BITMASK_SAS_EGM_AFT_STATUS_ENABLE_INHOUSE_TRANS				BIT_N(4)
#define BITMASK_SAS_EGM_AFT_STATUS_ENABLE_BONUS_TRANS				BIT_N(5)
#define BITMASK_SAS_EGM_AFT_STATUS_ENABLE_DEBIT_TRANS				BIT_N(6)
#define BITMASK_SAS_EGM_AFT_STATUS_ENABLE_ANY_AFT					BIT_N(7)

// SAS host cashout status (for AFT)
#define BITMASK_SAS_EGM_HOST_CASHOUT_STATUS_CTRL_BY_HOST	BIT_N(0)
#define BITMASK_SAS_EGM_HOST_CASHOUT_STATUS_ENABLED			BIT_N(1)
#define BITMASK_SAS_EGM_HOST_CASHOUT_STATUS_HARD_MODE		BIT_N(2)

// SAS AFT transfer flag (for AFT)
#define BITMASK_SAS_AFT_TRANS_FLAG_CASHOUT_CTRL_BY_HOST		BIT_N(0)
#define BITMASK_SAS_AFT_TRANS_FLAG_CASHOUT_ENABLED			BIT_N(1)
#define BITMASK_SAS_AFT_TRANS_FLAG_CASHOUT_MODE_HARD		BIT_N(2)
#define BITMASK_SAS_AFT_TRANS_FLAG_REQ_CASHOUT				BIT_N(3)
#define BITMASK_SAS_AFT_TRANS_FLAG_REQ_LOCK_AFTER_TRANS		BIT_N(4)
#define BITMASK_SAS_AFT_TRANS_FLAG_REQ_CUSTOM_TICKET_DATA	BIT_N(5)
#define BITMASK_SAS_AFT_TRANS_FLAG_REQ_TRANS_ON_LOCK		BIT_N(6)
#define BITMASK_SAS_AFT_TRANS_FLAG_REQ_RECEIPT				BIT_N(7)


/* Define enum here */
enum SAS_PORT {
	SAS_PORT_1 = 0,
	SAS_PORT_2 = 1,
	SAS_PORT_3 = 2,
	SAS_PORT_ALL = 0xFF,
};

enum SAS_METER_TYPE {
	SAS_METER_TYPE_MACHINE = 0,
	SAS_METER_TYPE_PER_GAME,
	SAS_METER_TYPE_PER_DENOM,
};

enum SAS_METER_SET_MODE {
	SAS_METER_MODE_INCREASE = 0,
	SAS_METER_MODE_DECREASE,
	SAS_METER_MODE_REPLACE,
	SAS_METER_MODE_RESET,
};

enum SAS_WON_METER_TYPE {
	SAS_WON_METER_TYPE_PAYTABLE_WIN_WITHOUT_HANDPAY = 0,
	SAS_WON_METER_TYPE_PROG_WIN_WITHOUT_HANDPAY = 1,
	SAS_WON_METER_TYPE_BONUS_WIN_WITHOUT_HANDPAY = 2,
	SAS_WON_METER_TYPE_PAYTABLE_WIN_WITH_HANDPAY = 3,
	SAS_WON_METER_TYPE_PROG_WIN_WITH_HANDPAY = 4,
	SAS_WON_METER_TYPE_BONUS_WIN_WITH_HANDPAY = 5,
};

enum SAS_CREDIT_TYPE {
	SAS_CREDIT_CASHABLE = 0,
	SAS_CREDIT_RESTRICTED = 1,
	SAS_CREDIT_NONRESTRICTED = 2,
};

enum SAS_ROM_SIG_MECHA {
	SAS_ROM_SIG_MECHA_STANDARD = 0,
	SAS_ROM_SIG_MECHA_REBOOT_REMAIN = 1,
};

enum SAS_HANDPAY_LEVEL {
	SAS_HANDPAY_LEVEL_NON_PROG_WIN = 0x00,
	SAS_HANDPAY_LEVEL_NON_PROG_TOP_WIN = 0x40,
	SAS_HANDPAY_LEVEL_CANCELLED_CREDITS = 0x80,
};

enum SAS_HANDPAY_VALID_TYPE {
	SAS_HANDPAY_VALID_JACKPOT = 0,
	SAS_HANDPAY_VALID_CASHOUT = 1,
	SAS_HANDPAY_VALID_JACKPOT_WITH_PROG_AMOUNT = 2,
};

enum SAS_HANDPAY_MODE {
	SAS_HANDPAY_MODE_NORMAL = 0,
	SAS_HANDPAY_MODE_LEGACY = 1,
};

enum SAS_TICKET_REDEEM_RESULT {
	SAS_TICKET_REDEEM_RESULT_PENDING = 0,
	SAS_TICKET_REDEEM_RESULT_HOST_REJECT = 1,
	SAS_TICKET_REDEEM_RESULT_LP70_TIMEOUT = 2,
	SAS_TICKET_REDEEM_RESULT_LP71_TIMEOUT = 3,
	SAS_TICKET_REDEEM_RESULT_LINK_DOWN = 4,
};

enum SAS_COMP_REDEEM_STATUS {
	SAS_COMP_REDEEM_STATUS_CASHABLE_TICKET_REDEEMED = 0x00,
	SAS_COMP_REDEEM_STATUS_RES_TICKET_REDEEMED = 0x01,
	SAS_COMP_REDEEM_STATUS_NONRES_TICKET_REDEEMED = 0x02,
	SAS_COMP_REDEEM_STATUS_REJECT_BY_HOST = 0x80,
	SAS_COMP_REDEEM_STATUS_VALID_NUM_NOT_MATCH = 0x81,
	SAS_COMP_REDEEM_STATUS_NOT_VALID_TRANS_FUNC = 0x82,
	SAS_COMP_REDEEM_STATUS_NOT_VALID_AMOUNT = 0x83,
	SAS_COMP_REDEEM_STATUS_AMOUNT_EXCEED_CREDIT_LIMIT = 0x84,
	SAS_COMP_REDEEM_STATUS_AMOUNT_NOT_EVEN_MULTIPLE_OF_DENOM = 0x85,
	SAS_COMP_REDEEM_STATUS_AMOUNT_NOT_MATCH = 0x86,
	SAS_COMP_REDEEM_STATUS_UNABLE_ACCEPT_THIS_TIME = 0x87,
	SAS_COMP_REDEEM_STATUS_TIMEOUT = 0x88,
	SAS_COMP_REDEEM_STATUS_LINK_DOWN = 0x89,
	SAS_COMP_REDEEM_STATUS_REDEEM_DISABLED = 0x8A,
	SAS_COMP_REDEEM_STATUS_VALIDATOR_FAILURE = 0x8B,
};

enum SAS_TICKET_PREP_PRINT_TYPE {
	SAS_TICKET_PREP_PRINT_TYPE_CASHABLE = 0,
	SAS_TICKET_PREP_PRINT_TYPE_RESTRICTED = 1,
};

enum SAS_TICKET_PREP_PRINT_RESULT {
	SAS_TICKET_PREP_PRINT_RESULT_HOST_ALLOW = 0,
	SAS_TICKET_PREP_PRINT_RESULT_HOST_REJECT = 3,
	SAS_TICKET_PREP_PRINT_RESULT_HOST_TIMEOUT = 4,
	SAS_TICKET_PREP_PRINT_RESULT_LINK_DOWN = 5,
};

enum SAS_TICKET_TYPE {
	SAS_TICKET_TYPE_CASHABLE_CASHOUT = 0x00,
	SAS_TICKET_TYPE_RESTRICTED_CASHOUT = 0x01, 
	SAS_TICKET_TYPE_INHOUSE_CASHABLE_AFT = 0x02,
	SAS_TICKET_TYPE_INHOUSE_RESTRICTED_AFT = 0x03,
	SAS_TICKET_TYPE_DEBIT_AFT = 0x04,
	SAS_TICKET_TYPE_CASHABLE_REDEEM = 0x80,
	SAS_TICKET_TYPE_RESTRICTED_REDEEM = 0x81,
	SAS_TICKET_TYPE_NONRESTRICTED_REDEEM = 0x82,
};

enum SAS_AFT_REG_ACTION {
	SAS_AFT_REG_ACTION_REQUEST = 0,
	SAS_AFT_REG_ACTION_CANCEL,
	SAS_AFT_REG_ACTION_ACK,
};

enum SAS_AFT_LOCK_ACTION {
	SAS_AFT_LOCK_ACTION_UNLOCKED = 0,
	SAS_AFT_LOCK_ACTION_LOCKED = 1,
};

enum SAS_AFT_EGM_STATUS {
	SAS_AFT_EGM_AVAIL_TRANS_STATUS = 0,
	SAS_AFT_EGM_AFT_STATUS = 1,
	SAS_AFT_EGM_HOST_CASHOUT_STATUS = 2,
};

enum SAS_AFT_HOST_CASHOUT_TYPE {
	SAS_AFT_HOST_CASHOUT_TYPE_CASHOUT = 0,
	SAS_AFT_HOST_CASHOUT_TYPE_CASHOUT_WIN = 1,
};

enum SAS_AFT_TRANS_TYPE {
	SAS_AFT_TRANS_TYPE_INHOUSE_TO_EGM = 0x00,
	SAS_AFT_TRANS_TYPE_BONUS_COIN_OUT_WIN_TO_EGM = 0x10,
	SAS_AFT_TRANS_TYPE_BONUS_JACKPOT_WIN_TO_EGM = 0x11,
	SAS_AFT_TRANS_TYPE_INHOUSE_TO_TICKET = 0x20,
	SAS_AFT_TRANS_TYPE_DEBIT_TO_EGM = 0x40,
	SAS_AFT_TRANS_TYPE_DEBIT_TO_TICKET = 0x60,
	SAS_AFT_TRANS_TYPE_INHOUSE_TO_HOST = 0x80,
	SAS_AFT_TRANS_TYPE_WIN_AMOUNT_TO_HOST = 0x90,
};

enum SAS_AFT_REJECT_STATUS {
	SAS_AFT_REJECT_STATUS_HOST_CASHOUT_TIMEOUT = 0x00,
	SAS_AFT_REJECT_STATUS_HOST_CASHOUT_CANCEL_BY_HOST = 0x01,
	SAS_AFT_REJECT_STATUS_HOST_CASHOUT_REJECT_BY_HOST = 0x02,
};

enum SAS_AFT_COMP_TRANS_STATUS {
	SAS_AFT_COMP_TRANS_STATUS_FULL_TRANS_SUCCESS = 0x00,
	SAS_AFT_COMP_TRANS_STATUS_PARTIAL_TRANS_SUCCESS = 0x01,
	SAS_AFT_COMP_TRANS_STATUS_CANCEL_BY_HOST = 0x80,
	SAS_AFT_COMP_TRANS_STATUS_TRANSACTION_ID_NOT_UNIQUE = 0x81,
	SAS_AFT_COMP_TRANS_STATUS_NOT_VALID_TRANS_FUNC = 0x82,				
	SAS_AFT_COMP_TRANS_STATUS_NOT_VALID_AMOUNT_EXPIR = 0x83,
	SAS_AFT_COMP_TRANS_STATUS_AMOUNT_EXCEED_TRANS_LIMIT = 0x84,
	SAS_AFT_COMP_TRANS_STATUS_AMOUNT_NOT_EVEN_MULTIPLE_OF_DENOM = 0x85, 
	SAS_AFT_COMP_TRANS_STATUS_UNABLE_DO_PARTIAL_TRANS_TO_HOST = 0x86,	
	SAS_AFT_COMP_TRANS_STATUS_UNABLE_DO_TRANS_THIS_TIME = 0x87,
	SAS_AFT_COMP_TRANS_STATUS_EGM_NOT_REGISTERED = 0x88,
	SAS_AFT_COMP_TRANS_STATUS_REG_KEY_NOT_MATCH = 0x89,
	SAS_AFT_COMP_TRANS_STATUS_NO_POS_ID = 0x8A,
	SAS_AFT_COMP_TRANS_STATUS_NO_WON_CREDIT_AVAIL_FOR_CASHOUT = 0x8B,
	SAS_AFT_COMP_TRANS_STATUS_NO_DENOM_SET = 0x8C,
	SAS_AFT_COMP_TRANS_STATUS_EXPIR_NOT_VALID_FOR_TICKET = 0x8D,
	SAS_AFT_COMP_TRANS_STATUS_TRANS_TO_TICKET_DEVICE_NOT_AVAIL = 0x8E,
	SAS_AFT_COMP_TRANS_STATUS_RESTRICTED_POOL_NOT_MATCH = 0x8F,
	SAS_AFT_COMP_TRANS_STATUS_UNABLE_PRINT_RECEIPT = 0x90,
	SAS_AFT_COMP_TRANS_STATUS_RECEIPT_DATA_MISSING = 0x91,
	SAS_AFT_COMP_TRANS_STATUS_RECEIPT_NOT_ALLOW_FOR_BONUS_TRANS = 0x92,
	SAS_AFT_COMP_TRANS_STATUS_ASSET_NUM_NOT_SET_OR_NOT_MATCH = 0x93,
	SAS_AFT_COMP_TRANS_STATUS_NOT_LOCKED = 0x94,
	SAS_AFT_COMP_TRANS_STATUS_TRANSACTION_ID_NOT_VALID = 0x95,
	SAS_AFT_COMP_TRANS_STATUS_UNEXPECTED_ERR = 0x9F,
};

enum SAS_NVRAM_ERR_TYPE {
	SAS_NVRAM_ERR_CMOS_RAM_DATA_RECOVERED = 0,
	SAS_NVRAM_ERR_CMOS_RAM_DATA_LOST,
	SAS_NVRAM_ERR_CMOS_RAM_BAD_DEVICE,
};

enum SAS_INTR_TYPE {
	SAS_INTR_FINISH_SYNC = 0x01,
	SAS_INTR_LINK_DOWN = 0x02,
	SAS_INTR_HOST_SET_RTE_MODE = 0x03,
	SAS_INTR_EC_QUEUE_FULL = 0x04,

	SAS_INTR_MACHINE_STATUS_CHANGE = 0x10,
	SAS_INTR_ROM_SIG_REQUEST = 0x11,
	SAS_INTR_BILL_DENOM_STATUS_CHANGE = 0x12,
	SAS_INTR_EN_DIS_GAME_N = 0x13,
	SAS_INTR_GAME_DELAY = 0x14,
	SAS_INTR_SET_DATE_TIME = 0x15,
	SAS_INTR_ENABLE_BA_REQUEST = 0x16,

	SAS_INTR_TICKET_REDEEM_RESULT = 0x20,
	SAS_INTR_TICKET_REDEEM_FINISHED = 0x21,

	SAS_INTR_EXT_VALID_STATUS_CHANGE = 0x30,
	SAS_INTR_PREP_TICKET_PRINT_RESULT = 0x32,
	SAS_INTR_VALID_QUEUE_FULL = 0x33,
	SAS_INTR_SEC_VALID_NUM_SET = 0x34,
	SAS_INTR_HOST_CANCEL_VALID_CFG = 0x35,

	SAS_INTR_GET_LEGACY_BONUS = 0x40,

	SAS_INTR_GET_AFT_REGISTER_INFO = 0x50,
	SAS_INTR_GET_AFT_LOCK_INFO = 0x51,

	SAS_INTR_AFT_TRANS_PENDING = 0x53,
	SAS_INTR_AFT_TRANS_FINISHED = 0x54,
	SAS_INTR_AFT_HOST_CASHOUT_STATUS_CHANGE = 0x55,
	SAS_INTR_AFT_TRANS_REJECT = 0x56,
	SAS_INTR_AFT_TRANS_HOST_REQ_CANCEL = 0x57,

	SAS_INTR_PROG_WIN_RECORD_QUEUE_FULL = 0x60,
	SAS_INTR_PROG_LINK_STATUS_CHANGE = 0x61,

	SAS_INTR_DETECT_NVRAM_ERROR = 0xF0,
};

/* Start Define SAS Status */ 
enum SAS_STATUS_TYPE {
	SAS_STATUS_LINK = 0,
	SAS_STATUS_ROM_SIG = 1,
	SAS_STATUS_EXCEPTION_QUEUE = 2,
	SAS_STATUS_HANDPAY_PROC = 3,
	SAS_STATUS_HANDPAY_QUEUE = 4,
	SAS_STATUS_TI_PROC = 5,
	SAS_STATUS_PREP_TO_PROC = 6,
	SAS_STATUS_VALID_RECORD_QUEUE = 7,
	SAS_STATUS_LEGACY_BONUS = 8,
	SAS_STATUS_MACHINE_CFG = 9,
	SAS_STATUS_BILL_DENOM_CFG = 10,
	SAS_STATUS_DATE_TIME = 11,

	SAS_STATUS_SEC_VALID_NUM = 13,
	SAS_STATUS_GAME_ENABLE = 14,
	SAS_STATUS_AFT_REGISTER = 15,
	SAS_STATUS_AFT_LOCK = 16,
	SAS_STATUS_AFT_TRANS_PROC = 17,

	SAS_STATUS_PROG_QUEUE = 30,
	SAS_STATUS_PROG_LINK = 31,

	SAS_STATUS_NVRAM = 99,
	SAS_STATUS_END,
};

enum SAS_LINK_STATUS {
	SAS_LINK_STATUS_NORMAL = 0,
	SAS_LINK_STATUS_NO_SYNC = 1,
	SAS_LINK_STATUS_LINK_DOWN_5S_NO_ADDR = 2,
	SAS_LINK_STATUS_LINK_DOWN_30S_NO_ACK = 3,
};

enum SAS_ROM_SIG_STATUS {
	SAS_ROM_SIG_STATUS_IDLE = 0,
	SAS_ROM_SIG_STATUS_REQ = 1,
};

enum SAS_HP_PROC_STATUS {
	SAS_HP_PROC_STATUS_IDLE	= 0,
	SAS_HP_PROC_STATUS_WAIT_RESET = 1,
};

enum SAS_TI_PROC_STATUS {
	SAS_TI_PROC_STATUS_IDLE = 0,
	SAS_TI_PROC_STATUS_WAIT_HOST = 1,
	SAS_TI_PROC_STATUS_PENDING = 2,
	SAS_TI_PROC_STATUS_WAIT_FINISH = 3,
	SAS_TI_PROC_STATUS_HOST_REJECT = 4,
	SAS_TI_PROC_STATUS_HOST_TIMEOUT = 5,
	SAS_TI_PROC_STATUS_LINK_DOWN = 6,
};

enum SAS_PREP_TO_PROC_STATUS {
	SAS_PREP_TO_PROC_STATUS_IDLE = 0,
	SAS_PREP_TO_PROC_STATUS_WAIT_HOST = 1,
	SAS_PREP_TO_PROC_STATUS_HOST_ALLOW = 2,
	SAS_PREP_TO_PROC_STATUS_HOST_REJECT = 3,
	SAS_PREP_TO_PROC_STATUS_HOST_TIMEOUT = 4,
	SAS_PREP_TO_PROC_STATUS_HOST_LINK_DOWN = 5,
};

enum SAS_LEGACY_BONUS_STATUS {
	SAS_LEGACY_BONUS_STATUS_NONE = 0,
	SAS_LEGACY_BONUS_STATUS_REQ = 1,
};

enum SAS_MACHINE_CFG_STATUS {
	SAS_MACHINE_CFG_STATUS_NO_CHANGE = 0,
	SAS_MACHINE_CFG_STATUS_CHANGE = 1,
};

enum SAS_BILL_DENOM_CFG_STATUS {
	SAS_BILL_DENOM_CFG_STATUS_NO_CHANGE = 0,
	SAS_BILL_DENOM_CFG_STATUS_CHANGE = 1,
};

enum SAS_DATE_TIME_STATUS {
	SAS_DATE_TIME_STATUS_NO_CHANGE = 0,
	SAS_DATE_TIME_STATUS_CHANGE = 1,
};

enum SAS_SEC_VALID_NUM_STATUS {
	SAS_SEC_VALID_NUM_STATUS_SET = 0,
	SAS_SEC_VALID_NUM_STATUS_NOT_SET = 1,
};

enum SAS_GAME_ENABLE_STATUS {
	SAS_GAME_ENABLE_STATUS_NO_CHANGE = 0,
	SAS_GAME_ENABLE_STATUS_CHANGE = 1,
};

enum SAS_AFT_REGISTER_STATUS {
	SAS_AFT_REG_STATUS_UNREGISTER = 0,
	SAS_AFT_REG_STATUS_PENDING = 1,
	SAS_AFT_REG_STATUS_REGISTERED = 2,
};

enum SAS_AFT_LOCK_STATUS {
	SAS_AFT_LOCK_STATUS_NOT_LOCKED = 0,
	SAS_AFT_LOCK_STATUS_PENDING = 1,
	SAS_AFT_LOCK_STATUS_LOCKED = 2,
};

enum SAS_AFT_TRANS_PROC_STATUS {
	SAS_AFT_TRANS_PROC_STATUS_IDLE = 0,
	SAS_AFT_TRANS_PROC_STATUS_WAIT_CASHOUT_TRANS = 1,
	SAS_AFT_TRANS_PROC_STATUS_PENDING = 2,
	SAS_AFT_TRANS_PROC_STATUS_WAIT_RECEIPT = 3,
	SAS_AFT_TRANS_PROC_STATUS_WAIT_FINISH = 4,
};

enum SAS_PROG_LINK_STATUS {
	SAS_PROG_LINK_STATUS_NORMAL = 0,
	SAS_PROG_LINK_STATUS_DOWN = 1,
};

enum SAS_NVRAM_STATUS {
	SAS_NVRAM_STATUS_NORMAL = 0,
	SAS_NVRAM_STATUS_CFG_ERR_ONLY = 1,
	SAS_NVRAM_STATUS_METER_ERR_ONLY = 2,
	SAS_NVRAM_STATUS_ALL_ERR = 3,
	SAS_NVRAM_STATUS_UNKNOWN = 4,
};
/* End Define SAS Status */

/* API for Initial SAS Handler */
GLU32 DLLEXPORT GXG_SAS_Init();
GLU32 DLLEXPORT GXG_SAS_Release();
GLU32 DLLEXPORT GXG_SAS_GetAPIVersion(char *ver);
GLU32 DLLEXPORT GXG_SAS_GetDriverVersion(char *ver);
GLU32 DLLEXPORT GXG_SAS_GetFirmwareVersion(char *ver);

/* API for SAS Control */
GLU32 DLLEXPORT GXG_SAS_SetEnabled(GLU8 port_num, GLU8 enabled);
GLU32 DLLEXPORT GXG_SAS_SetLPEnabled(GLU8 lp_cmd, GLU8 enabled);
GLU32 DLLEXPORT GXG_SAS_SetEGMAddr(GLU8 port_num, GLU8 addr);
GLU32 DLLEXPORT GXG_SAS_EnableCmdCRCErrNACK(GLU8 port_num, GLU8 enabled);
GLU32 DLLEXPORT GXG_SAS_SetIntrEnabled(GLU8 enabled, GLU8 *intr_list, GLU8 list_size);
GLU32 DLLEXPORT GXG_SAS_GetStatus(GLU8 port_num, GLU8 type, GLU8 *status, void *status_data);

/* API for SAS Basic Configuration */
GLU32 DLLEXPORT GXG_SAS_ResetDefault();
GLU32 DLLEXPORT GXG_SAS_SetGameInfo(GLU8 total_game_num, GLU32 enabled_game_mask);
GLU32 DLLEXPORT GXG_SAS_GetGameInfo(GLU8 *total_game_num, GLU32 *enabled_game_mask);
GLU32 DLLEXPORT GXG_SAS_SetCurrentSelectGame(GLU8 game_num);
GLU32 DLLEXPORT GXG_SAS_GetCurrentSelectGame(GLU8 *game_num);
GLU32 DLLEXPORT GXG_SAS_GetLastSelectGame(GLU8 *game_num);
GLU32 DLLEXPORT GXG_SAS_SetEnabledGameMask(GLU32 game_mask);
GLU32 DLLEXPORT GXG_SAS_GetEnabledGameMask(GLU32 *game_mask);
GLU32 DLLEXPORT GXG_SAS_SetGameDetail(GLU8 game_num, SAS_GAME_DETAIL game_detail);
GLU32 DLLEXPORT GXG_SAS_GetGameDetail(GLU8 game_num, SAS_GAME_DETAIL *game_detail);
GLU32 DLLEXPORT GXG_SAS_SetFeatureCode(GLU8 game_num, GLU8 *features);
GLU32 DLLEXPORT GXG_SAS_GetFeatureCode(GLU8 game_num, GLU8 *features);
GLU32 DLLEXPORT GXG_SAS_SetFeature(GLU8 game_num, GLU32 feature);
GLU32 DLLEXPORT GXG_SAS_GetFeature(GLU8 game_num, GLU32 *feature);
GLU32 DLLEXPORT GXG_SAS_SetEGMInfo(GLU8 sas_denom, GLU8 token_denom, char *serial_num);
GLU32 DLLEXPORT GXG_SAS_GetEGMInfo(GLU8 *sas_denom, GLU8 *token_denom, char *serial_num);
GLU32 DLLEXPORT GXG_SAS_SetDefaultTicketData(SAS_TICKET_DATA tito_data);
GLU32 DLLEXPORT GXG_SAS_GetDefaultTicketData(SAS_TICKET_DATA *tito_data);
GLU32 DLLEXPORT GXG_SAS_SetAssetNumber(GLU32 asset_num);
GLU32 DLLEXPORT GXG_SAS_GetAssetNumber(GLU32 *asset_num);
GLU32 DLLEXPORT GXG_SAS_GetHostCtrlMachineStatus(GLU16 *status);
GLU32 DLLEXPORT GXG_SAS_GetHostCfgBillDenom(GLU32 *denom_cfg, GLU8 *action_flag);
GLU32 DLLEXPORT GXG_SAS_SetDateTime(GLU32 *datetime);
GLU32 DLLEXPORT GXG_SAS_GetDateTime(GLU32 *datetime);
GLU32 DLLEXPORT GXG_SAS_SetSASDenom(GLU8 denom_code);
GLU32 DLLEXPORT GXG_SAS_GetSASDenom(GLU8 *denom_code);
GLU32 DLLEXPORT GXG_SAS_SetTokenDenom(GLU8 denom_code);
GLU32 DLLEXPORT GXG_SAS_GetTokenDenom(GLU8 *denom_code);
GLU32 DLLEXPORT GXG_SAS_GetPoolID(GLU16 *pool_id);
GLU32 DLLEXPORT GXG_SAS_SetCreditLimit(GLU64 value);
GLU32 DLLEXPORT GXG_SAS_GetCreditLimit(GLU64 *value);

/* API for SAS Multi-Denomination */
GLU32 DLLEXPORT GXG_SAS_AddGameDenom(GLU8 game_num, GLU8 denom_code, GLU16 max_bet);
GLU32 DLLEXPORT GXG_SAS_DelGameDenom(GLU8 game_num, GLU8 denom_code);
GLU32 DLLEXPORT GXG_SAS_SetCurrentGameDenom(GLU8 denom_code);
GLU32 DLLEXPORT GXG_SAS_GetCurrentGameDenom(GLU8 game_num, GLU8 *denom_code);
GLU32 DLLEXPORT GXG_SAS_GetEnabledGameDenomMask(GLU8 game_num, GLU64 *denom_mask);
GLU32 DLLEXPORT GXG_SAS_GetMaxBetByGameDenom(GLU8 game_num, GLU8 denom_code, GLU16 *max_bet);

/* API for Wager Category */
GLU32 DLLEXPORT GXG_SAS_SetSupWagerNum(GLU8 game_num, GLU8 sup_wager_num);
GLU32 DLLEXPORT GXG_SAS_GetSupWagerNum(GLU8 game_num, GLU8 *sup_wager_num);
GLU32 DLLEXPORT GXG_SAS_SetWagerCatPaybackPerc(GLU8 game_num, GLU8 wager_num, GLU16 payback_perc);
GLU32 DLLEXPORT GXG_SAS_GetWagerCatPaybackPerc(GLU8 game_num, GLU8 wager_num, GLU16 *payback_perc);

/* API for SAS Exception */
GLU32 DLLEXPORT GXG_SAS_InsertException(GLU8 port_num, GLU8 event_code);

/* API for Meter */
GLU32 DLLEXPORT GXG_SAS_SetMeter(SAS_METER_INFO meter_info);
GLU32 DLLEXPORT GXG_SAS_GetMeter(SAS_METER_INFO *meter_info);
GLU32 DLLEXPORT GXG_SAS_SetMeterEx(GLU8 meter_type, GLU8 num, GLU8 meter_code, GLU64 value);
GLU32 DLLEXPORT GXG_SAS_GetMeterEx(GLU8 meter_type, GLU8 num, GLU8 meter_code, GLU64 *value);

GLU32 DLLEXPORT GXG_SAS_SetMultiMeterByMode(SAS_METER_CLUSTER meter_cluster);

GLU32 DLLEXPORT GXG_SAS_IncMachineMeter(GLU8 meter_code, GLU64 value);
GLU32 DLLEXPORT GXG_SAS_DecMachineMeter(GLU8 meter_code, GLU64 value);
GLU32 DLLEXPORT GXG_SAS_SetMachineMeter(GLU8 meter_code, GLU64 value);

GLU32 DLLEXPORT GXG_SAS_IncGameMeter(GLU8 game_num, GLU8 meter_code, GLU64 value);
GLU32 DLLEXPORT GXG_SAS_SetGameMeter(GLU8 game_num, GLU8 meter_code, GLU64 value);

GLU32 DLLEXPORT GXG_SAS_IncDenomMeter(GLU8 denom_code, GLU8 meter_code, GLU64 value);
GLU32 DLLEXPORT GXG_SAS_SetDenomMeter(GLU8 denom_code, GLU8 meter_code, GLU64 value);

GLU32 DLLEXPORT GXG_SAS_IncWonMeter(GLU8 type, GLU64 amount);

GLU32 DLLEXPORT GXG_SAS_SetCurrentCedit(GLU8 type, GLU64 value);
GLU32 DLLEXPORT GXG_SAS_GetCurrentCedit(GLU8 type, GLU64 *value);

GLU32 DLLEXPORT GXG_SAS_ResetAllMeter();
GLU32 DLLEXPORT GXG_SAS_ResetBillMeter();

/* API for Hopper */
GLU32 DLLEXPORT GXG_SAS_SetHopperInfo(GLU8 status, GLU8 perc_full, GLU32 level);

/* API for Bill In & Coin In/Out */
GLU32 DLLEXPORT GXG_SAS_BillAccepted(GLU8 country_code, GLU8 denom_code, GLU8 to_hopper);
GLU32 DLLEXPORT GXG_SAS_CoinAccepted(GLU64 amount, GLU8 to_hopper);
GLU32 DLLEXPORT GXG_SAS_CoinPaid(GLU64 amount);

/* API for Poker/Card Game */
GLU32 DLLEXPORT GXG_SAS_SetCardInfo(GLU8 hand_type, GLU8 *hand);
GLU32 DLLEXPORT GXG_SAS_SetCardHeldStatus(GLU8 is_held, GLU8 card_index);

/* API for Physical Reel */
GLU32 DLLEXPORT GXG_SAS_SetPhyReelStopInfo(GLU8 total_num, GLU8 *position_list);

/* API for SAS ROM Signature */
GLU32 DLLEXPORT GXG_SAS_SetROMSig(GLU8 port_num, GLU16 sig, GLU16 seed);
GLU32 DLLEXPORT GXG_SAS_GetROMSigSeed(GLU8 port_num, GLU16* seed);
GLU32 DLLEXPORT GXG_SAS_SetROMSigMechanism(GLU8 mode);

/* API for SAS Handpay */
GLU32 DLLEXPORT GXG_SAS_SetHandpayMode(GLU8 mode);
GLU32 DLLEXPORT GXG_SAS_GetHandpayMode(GLU8 *mode);
GLU32 DLLEXPORT GXG_SAS_StartHandPay(SAS_HANDPAY_INFO hp_info);
GLU32 DLLEXPORT GXG_SAS_ResetHandPay(GLU32 *datetime, GLU8 has_receipt, GLU16 receipt_num);
GLU32 DLLEXPORT GXG_SAS_GetHandpayReceiptExpir(GLU32 *expir);

/* API for SAS TITO */
GLU32 DLLEXPORT GXG_SAS_SetValidPort(GLU8 port_num);
GLU32 DLLEXPORT GXG_SAS_GetValidPort(GLU8 *port_num);
GLU32 DLLEXPORT GXG_SAS_SetExtValidStatus(GLU8 egm_status);
GLU32 DLLEXPORT GXG_SAS_GetExtValidStatus(GLU8 *comb_status, GLU8 *egm_status, GLU8 *host_status);
GLU32 DLLEXPORT GXG_SAS_CancelValidCfg();
GLU32 DLLEXPORT GXG_SAS_GetTicketNum(GLU16 *num);
GLU32 DLLEXPORT GXG_SAS_ResetTicketNum(GLU16 num);
GLU32 DLLEXPORT GXG_SAS_GetTicketData(SAS_TICKET_DATA *ticket_data);
GLU32 DLLEXPORT GXG_SAS_GetChangeTicketResExpir(GLU32 *expir);
GLU32 DLLEXPORT GXG_SAS_PrepTicketPrint(GLU8 type, GLU64 amount, GLU8 *sec_valid_code);
GLU32 DLLEXPORT GXG_SAS_InsertTicketRecord(SAS_TICKET_RECORD ticket_record);
GLU32 DLLEXPORT GXG_SAS_StartTicketRedeem(char *barcode_data);
GLU32 DLLEXPORT GXG_SAS_CompleteTicketRedeem(GLU8 redeem_status);
GLU32 DLLEXPORT GXG_SAS_EnableChangeTicket(GLU8 enable);
GLU32 DLLEXPORT GXG_SAS_SetTicketCreditLimit(GLU64 value);
GLU32 DLLEXPORT GXG_SAS_GetTicketCreditLimit(GLU64 *value);

/* API for SAS Legacy Bonus */
GLU32 DLLEXPORT GXG_SAS_SetLegacyBonusPort(GLU8 port_num);
GLU32 DLLEXPORT GXG_SAS_GetLegacyBonusPort(GLU8 *port_num);
GLU32 DLLEXPORT GXG_SAS_SetEGMBusy(GLU8 flag);
GLU32 DLLEXPORT GXG_SAS_PayLegacyBonus(GLU64 amount, GLU8 tax_type, GLU8 is_handpay);
GLU32 DLLEXPORT GXG_SAS_GetCurrentLegacyBonus(GLU64 *amount, GLU8 *tax_type);
GLU32 DLLEXPORT GXG_SAS_GetGameDelay(GLU16 *delay_100ms);

/* API for SAS Game Event */
GLU32 DLLEXPORT GXG_SAS_GameStart(GLU64 bet_amount, GLU8 wager_cat_num);
GLU32 DLLEXPORT GXG_SAS_GameEnd(GLU64 win_amount);
GLU32 DLLEXPORT GXG_SAS_AccessGameRecall(GLU8 game_num, GLU16 index);

/* API for AFT */
GLU32 DLLEXPORT GXG_SAS_SetAFTPort(GLU8 port_num);
GLU32 DLLEXPORT GXG_SAS_GetAFTPort(GLU8 *port_num);
GLU32 DLLEXPORT GXG_SAS_SetAFTTransLimit(GLU64 value);
GLU32 DLLEXPORT GXG_SAS_GetAFTTransLimit(GLU64 *value);
GLU32 DLLEXPORT GXG_SAS_AFTRegisterAction(GLU8 action);
GLU32 DLLEXPORT GXG_SAS_GetAFTRegisterData(GLU8 *reg_key, GLU8 *pos_id);
GLU32 DLLEXPORT GXG_SAS_SetAFTEGMStatus(GLU8 type, GLU8 status);
GLU32 DLLEXPORT GXG_SAS_GetAFTEGMStatus(GLU8 type, GLU8 *status);
GLU32 DLLEXPORT GXG_SAS_SetAFTLockStatus(GLU8 status, GLU8 avail_trans);
GLU32 DLLEXPORT GXG_SAS_GetAFTTransData(SAS_AFT_TRANS_DATA *trans_data);
GLU32 DLLEXPORT GXG_SAS_GetAFTTransReceiptData(SAS_AFT_TRANS_RECEIPT_DATA *receipt_data);
GLU32 DLLEXPORT GXG_SAS_GetAFTReceiptData(SAS_AFT_RECEIPT_DATA *receipt_data);
GLU32 DLLEXPORT GXG_SAS_StartAFTHostCashout(GLU8 type);
GLU32 DLLEXPORT GXG_SAS_StopAFTHardHostCashout();
GLU32 DLLEXPORT GXG_SAS_CompleteAFTTrans(GLU8 trans_status, GLU64 cash_amount, GLU64 res_amount, GLU64 nonres_amount, GLU32 *datetime);
GLU32 DLLEXPORT GXG_SAS_CompleteAFTReceipt(GLU32 *datetime);

/* API for Progressive */
GLU32 DLLEXPORT GXG_SAS_SetProgPort(GLU8 port_num);
GLU32 DLLEXPORT GXG_SAS_GetProgPort(GLU8 *port_num);
GLU32 DLLEXPORT GXG_SAS_SetProgEnabled(GLU8 enabled);
GLU32 DLLEXPORT GXG_SAS_GetProgEnabled(GLU8 *enabled);
GLU32 DLLEXPORT GXG_SAS_SetProgGroupID(GLU8 group_id, GLU8 is_force);
GLU32 DLLEXPORT GXG_SAS_GetProgGroupID(GLU8 *group_id);
GLU32 DLLEXPORT GXG_SAS_SetProgEnabledLevel(GLU8 game_num, GLU32 level_mask);
GLU32 DLLEXPORT GXG_SAS_GetProgEnabledLevel(GLU8 game_num, GLU32 *level_mask);
GLU32 DLLEXPORT GXG_SAS_GetProgAmount(GLU8 level, GLU64 *amount);
GLU32 DLLEXPORT GXG_SAS_HitProgWin(GLU8 level, GLU64 amount, GLU8 is_handpay);
GLU32 DLLEXPORT GXG_SAS_GetAllProgAmount(GLU8 num, SAS_PROG_HIT_DATA *hit_data_list, GLU64 *total_amount);
GLU32 DLLEXPORT GXG_SAS_HitAllProgWin(GLU8 num, SAS_PROG_HIT_DATA *hit_data_list, GLU8 is_handpay);

/* API for NVRAM */
GLU32 DLLEXPORT GXG_SAS_VerifyNVRAM(GLU16 block_num, GLU16 length);
GLU32 DLLEXPORT GXG_SAS_EnableAutoNVRAMCheck(GLU8 enabled);
GLU32 DLLEXPORT GXG_SAS_ReadNVRAMBlock8(GLU32 offset, GLU8 length, GLU8 *buf);
GLU32 DLLEXPORT GXG_SAS_WriteNVRAMBlock8(GLU32 offset, GLU8 length, GLU8 *data);
GLU32 DLLEXPORT GXG_SAS_ReadNVRAMBlock16(GLU32 offset, GLU8 length, GLU16 *buf);
GLU32 DLLEXPORT GXG_SAS_WriteNVRAMBlock16(GLU32 offset, GLU8 length, GLU16 *data);
GLU32 DLLEXPORT GXG_SAS_ReadNVRAMBlock32(GLU32 offset, GLU8 length, GLU32 *buf);
GLU32 DLLEXPORT GXG_SAS_WriteNVRAMBlock32(GLU32 offset, GLU8 length, GLU32 *data);
GLU32 DLLEXPORT GXG_SAS_ReadNVRAMBlock64(GLU32 offset, GLU8 length, GLU64 *buf);
GLU32 DLLEXPORT GXG_SAS_WriteNVRAMBlock64(GLU32 offset, GLU8 length, GLU64 *data);
GLU32 DLLEXPORT GXG_SAS_InformNVRAMError(GLU8 type);
GLU32 DLLEXPORT GXG_SAS_CleanNVRAMError();

/* Other useful tools */
GLU32 DLLEXPORT GXG_SAS_EnableTraceTXRXMsg(GLU8 enabled);
GLU32 DLLEXPORT GXG_SAS_GetTXRXMsgRecord(GLU8 *port_num, GLU8 *is_tx, GLU16 *msg_len, GLU8 *msg_data);
GLU32 DLLEXPORT SASCreditToCent(GLU64 value, GLU8 denom_code, GLU64 *result);
GLU32 DLLEXPORT CentToSASCredit(GLU64 value, GLU8 denom_code, GLU64 *result);
GLU32 DLLEXPORT QwordToBCD(GLU64 value, GLU8 *result, GLU8 length);
GLU32 DLLEXPORT BCDToQword(GLU8 *bcd, GLU64 *result, GLU8 length);
GLU32 DLLEXPORT SetCurrentLocalTime(GLU32 *datetime);
GLU32 DLLEXPORT GetCurrentLocalTime(GLU32 *datetime);
GLU32 DLLEXPORT SetCurrentUTCTime(GLU32 *datetime);
GLU32 DLLEXPORT GetCurrentUTCTime(GLU32 *datetime);

/* Used for Testing Hardware */
GLU32 DLLEXPORT GXG_SAS_TestUart(GLU8 port_num);
GLU32 DLLEXPORT GXG_SAS_TestSRAM(GLU32 size, GLU8 mode);

/* Internal used */
GLU32 DLLEXPORT GXG_SAS_ReadSharedMemBlock32(GLU32 dwOffset, GLU32 dwLength, GLU32 *dwReadBuf);
GLU32 DLLEXPORT GXG_SAS_WriteSharedMemBlock32(GLU32 dwOffset, GLU32 dwLength, GLU32 *dwWriteBuf);


#ifdef __cplusplus
}
#endif    /*    __cplusplus    */

#endif
